name: Deploy Site

on:
  push:
    branches: ['main'] # or whatever

permissions:
  # IMPORTANT: this enables automatic authentication to the server
  id-token: write
  contents: read

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: internet-golf/deploy@v0.1.9
      - uses: pnpm/action-setup@v4
      - run: |
          pnpm i
          pnpm build
          golf create-deployment house-quiz.stuffedanimal.family --auth github-oidc
          golf deploy-content house-quiz.stuffedanimal.family --auth github-oidc --files ./build
